import { useState, useEffect, useRef, useCallback } from 'react';
const PAGED_POLYFILL_CDN = 'https://unpkg.com/pagedjs@0.4.3/dist/paged.polyfill.js';

const API_BASE = import.meta.env.VITE_API_URL ?? '';

const SAMPLE_CONTENT = {
  sections: [
    {
      title: 'Overview',
      subtitle: 'Sample report section',
      blocks: [
        { type: 'text', text: 'This is a sample text block for the report.' },
        {
          type: 'table',
          headers: ['Name', 'Value'],
          rows: [
            ['Item A', '100'],
            ['Item B', '200'],
          ],
        },
      ],
    },
  ],
};

export type ReportConfig = {
  pageSize: string;
  reportTitle: string;
  reportSubtitle: string;
  companyName: string;
  logo: string;
  footer: string;
  fontFamily: string;
  fontSize: string;
  lineHeight: string;
  bodyPadding: string;
  headerPadding: string;
  headerHeight: string;
  footerHeight: string;
  pageMargin: string;
  primaryColor: string;
  secondaryColor: string;
  googleMapsApiKey: string;
};

const DEFAULT_CONFIG: ReportConfig = {
  pageSize: 'A4',
  reportTitle: 'Quarterly Business Report',
  reportSubtitle: 'Q1 2025',
  companyName: 'Acme Inc.',
  logo: 'https://beta.canyoncorepath.com/assets/images/logo.png',
  footer: 'Confidential. Generated by Report Builder. © Acme Inc.',
  fontFamily: "'Segoe UI', system-ui, sans-serif",
  fontSize: '11pt',
  lineHeight: '1.5',
  bodyPadding: '0 16px',
  headerPadding: '12px 0',
  headerHeight: '18mm',
  footerHeight: '12mm',
  pageMargin: '24mm',
  primaryColor: '#2563eb',
  secondaryColor: '#64748b',
  googleMapsApiKey: '',
};

const PAGE_WIDTHS: Record<string, string> = {
  A3: '297mm',
  A4: '210mm',
  A5: '148mm',
  Letter: '216mm',
};
function getPageWidth(pageSize: string | undefined): string {
  const key = String(pageSize || 'A4').toUpperCase();
  return PAGE_WIDTHS[key] ?? PAGE_WIDTHS.A4;
}

type TabId = 'viewer' | 'content' | 'configuration';

export default function App() {
  const [tab, setTab] = useState<TabId>('viewer');
  const [templates, setTemplates] = useState<string[]>([]);
  const [template, setTemplate] = useState('default');
  const [content, setContent] = useState(JSON.stringify(SAMPLE_CONTENT, null, 2));
  const [config, setConfig] = useState<ReportConfig>(DEFAULT_CONFIG);
  const [htmlPreview, setHtmlPreview] = useState('');
  const [pdfBlobUrl, setPdfBlobUrl] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<'html' | 'pdf'>('html');
  const [error, setError] = useState('');
  const iframeRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    fetch(`${API_BASE}/reports/templates`)
      .then((r) => r.json())
      .then((d: { templates: string[] }) => {
        setTemplates(d.templates?.length ? d.templates : ['default']);
        if (d.templates?.length && !d.templates.includes(template)) {
          setTemplate(d.templates[0]);
        }
      })
      .catch(() => setTemplates(['default']));
  }, []);

  const configToPayload = (): Record<string, unknown> => ({
    pageSize: config.pageSize,
    reportTitle: config.reportTitle,
    reportSubtitle: config.reportSubtitle,
    companyName: config.companyName,
    logo: config.logo,
    footer: config.footer,
    fontFamily: config.fontFamily,
    fontSize: config.fontSize,
    lineHeight: config.lineHeight,
    bodyPadding: config.bodyPadding,
    headerPadding: config.headerPadding,
    headerHeight: config.headerHeight,
    footerHeight: config.footerHeight,
    pageMargin: config.pageMargin,
    primaryColor: config.primaryColor,
    secondaryColor: config.secondaryColor,
    googleMapsApiKey: config.googleMapsApiKey,
  });

  const handleRender = async () => {
    setError('');
    setHtmlPreview('');
    if (pdfBlobUrl) {
      URL.revokeObjectURL(pdfBlobUrl);
      setPdfBlobUrl(null);
    }
    let contentObj: Record<string, unknown>;
    try {
      contentObj = JSON.parse(content);
    } catch {
      setError('Invalid JSON in content');
      return;
    }
    const url = `${API_BASE}/reports/generate?format=html`;
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        template,
        content: contentObj,
        config: configToPayload(),
        options: { paged: true },
      }),
    });
    if (!res.ok) {
      setError(`Request failed: ${res.status}`);
      return;
    }
    const text = await res.text();
    setHtmlPreview(text);
    setViewMode('html');
  };

  const fetchPdfForView = async (): Promise<string | null> => {
    let contentObj: Record<string, unknown>;
    try {
      contentObj = JSON.parse(content);
    } catch {
      return null;
    }
    const res = await fetch(`${API_BASE}/reports/generate?format=pdf`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        template,
        content: contentObj,
        config: configToPayload(),
      }),
    });
    if (!res.ok) return null;
    const blob = await res.blob();
    return URL.createObjectURL(blob);
  };

  const handleViewPdf = async () => {
    if (pdfBlobUrl) {
      setViewMode('pdf');
      return;
    }
    setError('');
    const url = await fetchPdfForView();
    if (url) {
      if (pdfBlobUrl) URL.revokeObjectURL(pdfBlobUrl);
      setPdfBlobUrl(url);
      setViewMode('pdf');
    } else setError('Failed to load PDF');
  };

  const runPagedJs = useCallback(async () => {
    const doc = iframeRef.current?.contentDocument;
    if (!doc?.body) return;
    try {
      const res = await fetch(PAGED_POLYFILL_CDN);
      if (!res.ok) throw new Error('Polyfill fetch failed');
      const polyfillText = await res.text();
      if (polyfillText.trimStart().startsWith('<')) {
        throw new Error('Got HTML instead of script; check network or use CDN');
      }

      const configScript = doc.createElement('script');
      configScript.textContent = 'window.PagedConfig = window.PagedConfig || {}; window.PagedConfig.auto = false;';
      doc.body.appendChild(configScript);

      const polyfillScript = doc.createElement('script');
      polyfillScript.textContent = polyfillText;
      doc.body.appendChild(polyfillScript);

      const runScript = doc.createElement('script');
      runScript.textContent = `
(function() {
  function repeatTableHeaders() {
    var pages = document.querySelectorAll('.pagedjs_page');
    for (var i = 1; i < pages.length; i++) {
      var page = pages[i];
      var prevPage = pages[i - 1];
      var tables = page.querySelectorAll('table');
      var prevTables = prevPage.querySelectorAll('table');
      for (var j = 0; j < tables.length; j++) {
        var table = tables[j];
        if (table.querySelector('thead')) continue;
        var srcTable = prevTables[j];
        if (srcTable && srcTable.querySelector('thead')) {
          var clone = srcTable.querySelector('thead').cloneNode(true);
          table.insertBefore(clone, table.firstChild);
        }
      }
    }
  }
  if (window.PagedPolyfill && typeof window.PagedPolyfill.preview === 'function') {
    window.PagedPolyfill.preview().then(function() {
      repeatTableHeaders();
      var style = document.createElement('style');
      style.textContent = '.pagedjs_pages { display: flex; flex-direction: column; align-items: center; gap: 16px; } .pagedjs_page { box-shadow: 0 1px 4px rgba(0,0,0,0.12); }';
      document.head.appendChild(style);
    }).catch(function(e) { console.error('Paged.js preview failed', e); });
  }
})();
`;
      doc.body.appendChild(runScript);
    } catch (e) {
      console.error('Paged.js load failed', e);
    }
  }, []);

  const tabs: { id: TabId; label: string }[] = [
    { id: 'viewer', label: 'Viewer' },
    { id: 'content', label: 'Content' },
    { id: 'configuration', label: 'Configuration' },
  ];

  return (
    <div className="app">
      <header className="app-header">
        <h1>Report Viewer</h1>
        <nav className="tabs">
          {tabs.map((t) => (
            <button
              key={t.id}
              type="button"
              className={tab === t.id ? 'tab active' : 'tab'}
              onClick={() => setTab(t.id)}
            >
              {t.label}
            </button>
          ))}
        </nav>
        <div className="header-actions">
          <label className="header-label">
            Template
            <select
              value={template}
              onChange={(e) => setTemplate(e.target.value)}
            >
              {(templates.length ? templates : ['default']).map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
          </label>
          <div className="view-toggle">
            <button
              type="button"
              className={viewMode === 'html' ? 'btn btn-primary' : 'btn btn-secondary'}
              onClick={() => setViewMode('html')}
            >
              HTML
            </button>
            <button
              type="button"
              className={viewMode === 'pdf' ? 'btn btn-primary' : 'btn btn-secondary'}
              onClick={handleViewPdf}
            >
              PDF
            </button>
          </div>
          <button type="button" className="btn btn-primary" onClick={handleRender}>
            Render
          </button>
        </div>
      </header>

      {tab === 'viewer' && (
        <div className="tab-panel viewer-panel">
          {error && <p className="error">{error}</p>}
          {viewMode === 'html' && htmlPreview ? (
            <div
              className="preview-canvas preview-canvas--paged"
              style={{
                maxWidth: getPageWidth(config.pageSize),
              }}
            >
              <iframe
                ref={iframeRef}
                title="Report HTML preview"
                srcDoc={htmlPreview}
                onLoad={runPagedJs}
              />
            </div>
          ) : viewMode === 'pdf' && pdfBlobUrl ? (
            <div className="preview-canvas preview-canvas--pdf">
              <iframe title="Report PDF preview" src={pdfBlobUrl} />
            </div>
          ) : (
            <div className="preview-placeholder">
              {viewMode === 'pdf'
                ? 'Click Render, then switch to PDF view or click PDF above.'
                : 'Set content and configuration, then click Render to preview.'}
            </div>
          )}
        </div>
      )}

      {tab === 'content' && (
        <div className="tab-panel content-panel">
          <label className="panel-label">Content (JSON)</label>
          <textarea
            className="content-editor"
            value={content}
            onChange={(e) => setContent(e.target.value)}
            spellCheck={false}
          />
        </div>
      )}

      {tab === 'configuration' && (
        <div className="tab-panel config-panel">
          <form
            className="config-form"
            onSubmit={(e) => e.preventDefault()}
          >
            <fieldset>
              <legend>Report</legend>
              <label>Page size</label>
              <select
                value={config.pageSize}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, pageSize: e.target.value }))
                }
              >
                {['A3', 'A4', 'A5', 'Letter'].map((s) => (
                  <option key={s} value={s}>
                    {s}
                  </option>
                ))}
              </select>
              <label>Report title</label>
              <input
                value={config.reportTitle}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, reportTitle: e.target.value }))
                }
              />
              <label>Subtitle</label>
              <input
                value={config.reportSubtitle}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, reportSubtitle: e.target.value }))
                }
              />
              <label>Company name</label>
              <input
                value={config.companyName}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, companyName: e.target.value }))
                }
              />
              <label>Logo URL</label>
              <input
                value={config.logo}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, logo: e.target.value }))
                }
                placeholder="https://..."
              />
              <label>Footer text</label>
              <input
                value={config.footer}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, footer: e.target.value }))
                }
              />
            </fieldset>
            <fieldset>
              <legend>Colors</legend>
              <label>Primary color</label>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <input
                  type="color"
                  value={config.primaryColor}
                  onChange={(e) =>
                    setConfig((c) => ({ ...c, primaryColor: e.target.value }))
                  }
                  style={{ width: 40, height: 32, padding: 2, cursor: 'pointer' }}
                />
                <input
                  type="text"
                  value={config.primaryColor}
                  onChange={(e) =>
                    setConfig((c) => ({ ...c, primaryColor: e.target.value }))
                  }
                  style={{ flex: 1 }}
                />
              </div>
              <label>Secondary color</label>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <input
                  type="color"
                  value={config.secondaryColor}
                  onChange={(e) =>
                    setConfig((c) => ({ ...c, secondaryColor: e.target.value }))
                  }
                  style={{ width: 40, height: 32, padding: 2, cursor: 'pointer' }}
                />
                <input
                  type="text"
                  value={config.secondaryColor}
                  onChange={(e) =>
                    setConfig((c) => ({ ...c, secondaryColor: e.target.value }))
                  }
                  style={{ flex: 1 }}
                />
              </div>
            </fieldset>
            <fieldset>
              <legend>Fonts</legend>
              <label>Font family</label>
              <input
                value={config.fontFamily}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, fontFamily: e.target.value }))
                }
                placeholder="'Segoe UI', system-ui, sans-serif"
              />
              <label>Font size</label>
              <input
                value={config.fontSize}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, fontSize: e.target.value }))
                }
                placeholder="11pt"
              />
              <label>Line height</label>
              <input
                value={config.lineHeight}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, lineHeight: e.target.value }))
                }
                placeholder="1.5"
              />
            </fieldset>
            <fieldset>
              <legend>Padding & margin</legend>
              <label>Body padding</label>
              <input
                value={config.bodyPadding}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, bodyPadding: e.target.value }))
                }
                placeholder="0 16px"
              />
              <label>Header padding</label>
              <input
                value={config.headerPadding}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, headerPadding: e.target.value }))
                }
                placeholder="12px 0"
              />
              <label>Header height (print)</label>
              <input
                value={config.headerHeight}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, headerHeight: e.target.value }))
                }
                placeholder="18mm"
              />
              <label>Footer height (print)</label>
                <input
                  value={config.footerHeight}
                  onChange={(e) =>
                    setConfig((c) => ({ ...c, footerHeight: e.target.value }))
                  }
                  placeholder="12mm"
                />
              <label>Page margin</label>
              <input
                value={config.pageMargin}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, pageMargin: e.target.value }))
                }
                placeholder="24mm"
              />
            </fieldset>
            <fieldset>
              <legend>Maps</legend>
              <label>Google Maps API key</label>
              <input
                type="text"
                value={config.googleMapsApiKey}
                onChange={(e) =>
                  setConfig((c) => ({ ...c, googleMapsApiKey: e.target.value }))
                }
                placeholder="Optional – for map blocks"
              />
            </fieldset>
          </form>
        </div>
      )}
    </div>
  );
}
